### ISSUE TITLE
Automatically import the helpers

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-cli-simple-auth-testing#1]

**Comment by adamsrog** [comment]
Hi Marco,
I was just considering submitting a PR for this very issue.  

I'm interested in understanding why you think this isn't a good idea?  

Seems like it'd be reasonable to add these two lines to `tests/helpers/start-app.js` (probably after the `import config` line):
```javascript
import initializeTestHelpers from 'simple-auth-testing/test-helpers';
initializeTestHelpers();
```

Thanks for all your work on the `simple-auth` stuff!

**Comment by marcoow** [comment]
@adamsrog: I don't actually remember why I dropped the idea to be honest ;)

**Comment by adamsrog** [comment]
@marcoow thanks for the reply.  It is somewhat trivial, but it might be a step that some users overlook.  Want me to submit a PR?

**Comment by marcoow** [comment]
I guess it should be fine. Not sure how to do it with Ember CLI though…
