### ISSUE TITLE
Unable to find suitable version with 0.7.3

### ISSUE THREAD

**Issue by vire** [simplabs/ember-cli-simple-auth-testing#3]
running 

`ember install:addon ember-cli-simple-auth-testing`
or

`npm install --save-dev ember-cli-simple-auth-testing`
`ember generate ember-cli-simple-auth-testing`

leads to conflict

```
Installing browser packages via Bower...
  not-cached git://github.com/simplabs/ember-simple-auth-component.git#0.7.3
  resolved git://github.com/simplabs/ember-simple-auth-component.git#0.7.3
  conflict Unable to find suitable version for ember-simple-auth
    1) ember-simple-auth 0.7.2
    2) ember-simple-auth 0.7.3
[?] Answer: 
```

**Comment by marcoow** [comment]
You're updating from 0.7.2 to 0.7.3 - that's just how bower works.

**Comment by vire** [comment]
@marcoow kk thx for quick reponse,and sorry for creating this issue, I was just confused, because I've installed ember-simple-auth yesterday, and the ember-cli-simple-auth-testing today and since there was a release :).

And the question is, can I use ember-cli-simple-auth-testing latest to test routes using older versions of ember-cli-simple-auth ?

**Comment by marcoow** [comment]
You should not mix Ember Simple Auth versions so you should always install the base library plus all extension libraries simultaneously. Different versions might work together but nobody will ever test all the possible combinations.

**Comment by vire** [comment]
Thank you for the advice.
