### ISSUE TITLE
Unexpected end of input when using authenticateSession() helper.

### ISSUE THREAD

**Issue by Patrickmnts** [simplabs/ember-cli-simple-auth-testing#4]
My test suite is throwing the following error when utilizing the authenticateSession() helper.

```
Uncaught SyntaxError: Unexpected end of input at http://localhost:7357/3358/tests/index.html, line 0
```

Currently running:
ember-cli-simple-auth-testing 0.7.3
Ember 1.10.0
Ember CLI version 0.1.5

The content of my start-app.js is 
```
import Ember from 'ember';
import Application from '../../app';
import Router from '../../router';
import config from '../../config/environment';
import 'simple-auth-testing/test-helpers';

export default function startApp(attrs) {
  var application;

  var attributes = Ember.merge({}, config.APP);
  attributes = Ember.merge(attributes, attrs); // use defaults, but you can override;

  Ember.run(function() {
    application = Application.create(attributes);
    application.setupForTesting();
    application.injectTestHelpers();
  });

  return application;
}
```

config/environment.js within the if(environment === 'test') block.
```
ENV['simple-auth'] = {
      store: 'simple-auth-session-store:ephemeral'
    }
```

The error is thrown when the authenticateSession() helper is used as follows.

```
import Ember from 'ember';
import startApp from '../../helpers/start-app';

var application;

module('Acceptance: Account Page', {
  setup: function() {
    application = startApp();
  },
  teardown: function() {
    Ember.run(application, 'destroy');
  }
});

test('an authenticated user should be able to access /user/alerts', function(){
  authenticateSession();
  visit('user/alerts');
  andThen(function(){
    equal(currentPath(), 'user.alerts');
  });
});
```

**Comment by marcoow** [comment]
Do you have anything observing the session's `isAuthenticated` property maybe (maybe a `currentUser` property in a custom session or so)?

**Comment by Patrickmnts** [comment]
@marcoow I am not utilizing isAuthenticated in any of .property() declarations.  

I am utilizing {{/if session.isAuthenticated}} within the markup for certain conditionals...

**Comment by marcoow** [comment]
Can you post a stack trace?

**Comment by wereldbolt** [comment]
Same issue with a custom adapter for a model. Stacktrace:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at jQuery.parseJSON (http://localhost:4200/assets/vendor.js:8717:22)
    at ajaxConvert (http://localhost:4200/assets/vendor.js:9043:19)
    at done (http://localhost:4200/assets/vendor.js:9461:15)
    at XMLHttpRequest.jQuery.ajaxTransport.send.callback (http://localhost:4200/assets/vendor.js:9915:8)

Adapter:
import ApplicationAdapter from './application';
import config from '../config/environment';

export default ApplicationAdapter.extend({
	buildURL: function buildURL(type, id, record) {
		return 'http://localhost:4200/api/accounts/create';
	},
	ajax: function ajax(url, method, hash) {
		hash = hash || {};
        return this._super(url, method, hash);
	}
});

It works after changing the url to: http://localhost:4200/accounts/create

**Comment by Patrickmnts** [comment]
@wereldbolt That is an interesting find.  I have almost the exact same scenario taking place in my application adapter.

When I comment out the namespace: 'api' definition. The error no longer appears.

@marcoow is there a way to stub this out in a configuration for tests?

**Comment by marcoow** [comment]
Ember Simple Auth never uses any Ember Data functionality so this is a problem in your app's code that's u related to Ember Simple Auth. 

Looks like you need to mock these requests or are maybe mocking the wrong URL (the one without the namespace).
