### ISSUE TITLE
Can't find variable: invalidateSession

### ISSUE THREAD

**Issue by jonblack** [simplabs/ember-cli-simple-auth-testing#7]
Using `ember-cli-simple-auth-testing` version 0.8.0-beta.2 I get the following error when I try to use the helpers in a test:

    Acceptance | items: the route /items is inaccessible when the session is not authenticated
    ✘ Died on test #1     at http://localhost:7357/assets/test-support.js:2688
        at http://localhost:7357/assets/wishlist.js:2055
        at http://localhost:7357/assets/vendor.js:150
        at tryFinally (http://localhost:7357/assets/vendor.js:30)
        at http://localhost:7357/assets/vendor.js:156
        at http://localhost:7357/assets/test-loader.js:29
        at http://localhost:7357/assets/test-loader.js:21
        at http://localhost:7357/assets/test-loader.js:40
        at http://localhost:7357/assets/test-support.js:5460: Can't find variable: invalidateSession

The same code works when I use version 0.8.0-beta.1.

**Comment by marcoow** [comment]
Did you import the test helpers as described here https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-testing#installation ?

**Comment by jonblack** [comment]
Ok, I see what happened. There are four locations to get this information from:

* This repository
* [simplelabs Blog Post](http://log.simplabs.com/post/92824729750/testing-with-ember-simple-auth-and-ember-cli)
* [ember-cli-simple-auth-testing repository](https://github.com/simplabs/ember-cli-simple-auth-testing)
* [ember-cli-simple-auth-example repository](https://github.com/simplabs/ember-cli-simple-auth-example)

Only this repository has the correct import code for the beta.2 release. With all the similar names, I guess I never noticed what I was reading.

So, the README for this repository is correct. Thanks.

**Comment by marcoow** [comment]
Yes, that all is a bit messy currently but will get simpler once simplabs/ember-simple-auth#522 lands.
