### ISSUE TITLE
Setting secure data in the test authenticator

### ISSUE THREAD

**Issue by natecox** [simplabs/ember-cli-simple-auth-testing#8]
I have an acceptance test which relies on information stored in `session.content.secure.uid` in order to function properly, but I'm having issues gaining access to the secure key in testing.

A bit of research led me to a commit (https://github.com/simplabs/ember-simple-auth/commit/85e9808973b1a034eb36ae74978ac0c78fc9739f) stating that setting values on the secure keyword is not allowed, which makes it impossible for me to set what I need using `currentSession()`.

What is the accepted means of setting secure data on the session for testing, if there is one?

**Comment by marcoow** [comment]
Usually the content of the `secure` property is maintained by the session itself and is retrieved from the authenticator and/or store. For testing reasons it should be fine to set specific values in the `secure` property, you should just not set the `secure` property itself, e.g. `currentSession().set('secure.value', 'test')` should be fine.

**Comment by natecox** [comment]
If you attempt to set a value to `content.secure` or any of its children the request is simply ignored; I've tested this fairly extensively and have been able to set any other property on `session` except for `content.secure` or any child.

Part of my code sets a user profile on the session based off of the uid being passed back to me from a Firebase oAuth request. I don't want to actually make an external network call (and as far as I know I couldn't even if I wanted to) so I'd like to just set the session data that the authenticator would give me back manually.

**Comment by marcoow** [comment]
You'd have to use a custom authenticator then that you authenticate the session with and that resolves with the correct data you need for the test from the `authenticate` method.

**Comment by natecox** [comment]
Any idea how you set a custom authenticator for testing only? It already seems to be overriding the production authenticator with a "test" authenticator.

**Comment by marcoow** [comment]
It doesn't override the actual authenticator, it just adds one for testing - an application can have multiple authenticators. You could authenticate the session with a custom authenticator in a test with `currentSession().authenticate('authenticator:custom')`.

**Comment by natecox** [comment]
Ah, I don't know why that didn't occur to me. Thanks!
